version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: brightears_db
    environment:
      POSTGRES_USER: brightears
      POSTGRES_PASSWORD: brightears_dev
      POSTGRES_DB: brightears_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: